version: '3.8'
services:
  quarkus-blog:
    image: quarkus-blog:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sonny
      - POSTGRES_PASSWORD=sonny
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local